### ISSUE TITLE
Fix TestPrevoteTimeout

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#606]
# Problem
This test fails randomly with the following failure log.
https://github.com/clearmatics/autonity/blob/4258f2c8560fd93c806fae2886e81d06b9cc8b9d/consensus/tendermint/core/upon_condition_test.go#L552

```
--- FAIL: TestPrevoteTimeout (0.02s)
    --- FAIL: TestPrevoteTimeout/at_prevote_timeout_expiry_timeout_event_is_sent (0.00s)
        upon_condition_test.go:642: missing call(s) to *core.MockBackend.Post(is equal to {28 0xc00027fd00 1}) /home/pierspowlesland/projects/autonity/consensus/tendermint/core/upon_condition_test.go:638
        upon_condition_test.go:642: aborting test due to missing call(s)
```

# Acceptance Criteria

Running this test 100 times should not result in a single failure.

**Comment by aneequesafdar** [comment]
This testcase is failing because of the following lines of code:

https://github.com/clearmatics/autonity/blob/4258f2c8560fd93c806fae2886e81d06b9cc8b9d/consensus/tendermint/core/upon_condition_test.go#L639-L641

The test is expecting an event to be posted after the timeout has expired when the following line is called:
https://github.com/clearmatics/autonity/blob/4258f2c8560fd93c806fae2886e81d06b9cc8b9d/consensus/tendermint/core/upon_condition_test.go#L639

However, If the total time for timeout + duration to post the event is more than the sleep duration then the test will fail. Since this is machine-dependent I choose a difference of 1 millisecond which doesn't seem to be enough.

**Comment by piersy** [comment]
@aneequesafdar I'm seeing this problem again on develop.

See here - https://github.com/clearmatics/autonity/runs/1453133531?check_suite_focus=true

```--- FAIL: TestPrevoteTimeout (0.03s)
    --- PASS: TestPrevoteTimeout/prevote_timeout_started_after_quorum_of_prevotes_with_different_hashes (0.00s)
    --- PASS: TestPrevoteTimeout/prevote_timeout_is_not_started_multiple_times (0.00s)
    --- FAIL: TestPrevoteTimeout/at_prevote_timeout_expiry_timeout_event_is_sent (0.00s)
Error:         upon_condition_test.go:827: missing call(s) to *core.MockBackend.Post(is equal to {36 0xc00000f840 1}) /home/runner/work/autonity/autonity/consensus/tendermint/core/upon_condition_test.go:820
Error:         upon_condition_test.go:827: aborting test due to missing call(s)
```

**Comment by aneequesafdar** [comment]
I can try to further increase the timeout, however, that will increase the total duration of the test. Otherwise, we would need to improve our testing approach.

**Comment by aiman** [comment]
Let's try to reproduce this issue.
