### ISSUE TITLE
Network Permissionning

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#72]
Opening this issue to describe and discuss the current network permissionning approach.

### Rationale 

- The Autonity client is built around and for private network, hence network permissionning is a fundamental feature. 
- The network is symmetric, all the participant in the network have by default the same privileges than the others. Therefore [mutual authentication](https://en.wikipedia.org/wiki/Mutual_authentication) is required.
 
### Description and rules

Currently, network permissionning is using the Glienecke smart-contract interface to retrieve the list of authorized enodes. However, in a blockchain context, where there is no guarantee of synchronized node state, the enforcement of is not straightforward: the NodeID by itself is not sufficient, we need to know as well how far ahead of us a peer is, and this information can be only retrieved post Ethereum sub-protocol handshake via the total difficulty parameter.    
I will give some example later.

Description of the currently implemented protocol:

- The Ethereum service is updating an internal whitelist via the Glienecke contract before block insertion.
- We try dialing every enodes present in the whitelist on a periodic basis. 
- At DevP2P layer, RLPx ensures that a peer possesses the private key associated with his disclosed NodeId. ECDH is being used to establish a secure shared AES session key for encrypting all futures packets.   
- After successful authentication at DevP2P layer, ETH sub protocol will initiate a handshake, the current total difficulty will be exchanged, which is equal to the chain height with xBFT.  Then the following rules are enforced :

1. If the peer total difficulty is greater than ours we accept the incoming connection
2. If the peer is present in the local whitelist we accept the incoming connection. Previously I was only checking the NodeID but @JekaMas introduced a check on the IP address as well.

Otherwise, the connection is rejected.

### Potential issue and vulnerabilities

- The current implementation is unfinished, we need to stop relaying data when synchronizing. Indeed a malicious peer could fake its TD or a connection can be attempted on a previously authorized peer.   

I will update the document to reflect as well the changes that were made with the new enode format.

### Existing attacks
* https://github.com/clearmatics/autonity/pull/71

**Comment by JekaMas** [comment]
Looks like that step `If the peer total difficulty is greater than ours we accept the incoming connection` needs an additional check. Maybe we should ask a new peer to send the highest block header with valid signs and the proven state of the Glienecke contract where the peer is listed in the whitelist. And only if the peer managed to proof its state in the list we should start sync process.

**Comment by yazzaoui** [comment]
The problem with this approach is that we don't know who are the signers for this height, they might have changed and the only way to know it is to retrieve the full header-chain until the latest height.
As I proposed in the issue, I think we need to pause relaying (tx pools & blocks) until we are sync. Also If the chain is invalid we can blacklist the peer.

**Comment by JekaMas** [comment]
Or we just need the security property the same as Tendermint has: at any block only less than 1/3 of validators can be changed. If we have the property we can rely on sigratutes.

**Comment by yazzaoui** [comment]
> Or we just need the security property the same as Tendermint has: at any block only less than 1/3 of validators can be changed. If we have the property we can rely on sigratutes.

So after 3 blocks the whole validator set can be modified, right?

> Is it safe? It looks like that a malicious user could stop entire network.
If the malicious guy send a very high TD, we will try to sync with him and as long as the downloaded chain is valid then that's fine, when the received blocks are no longer valid then we blacklist.

**Comment by JekaMas** [comment]
I was thinking that someone can use a kind of Sybille attack: infinetely create peers, try to connect to the cluster, say that he got higher td and just wait. It each try will stop the network even for a small amount of time, eventually it'll stop the network.
The other thing is about how to differ a malicious user and a good guy with bad connection/server fail etc? It'll be banned too.

**Comment by yazzaoui** [comment]
The DoS attack is a valid point, I'll think about that :thinking:

**Comment by yazzaoui** [comment]
If we ban the ip address isn’t it enough ?

**Comment by JekaMas** [comment]
As I can understand, making new and new malicious peers is cheap and easy, so ban won't help to restore liveness of the network.
The second thing is how can we distinguish a good and feir peer with bad connection from malicious?

**Comment by yazzaoui** [comment]
I think we can find a way to make the ban costly, one idea:
- Ban temporally slow peers (eventually malicious) the IP range /24. If a good guy is too slow, ban anyway.
- Permanent ban (or very long) malicious peer IP range /24 sending invalid blocks.

Do you see any other option?

**Comment by JekaMas** [comment]
It looks like banning Telegram in Russia - https://usher2.club/en/ . They even tried to ban by /16 and /8, however, it doesn't work well and changing IPs in AWS is fast and cheap.

The thing is nowadays the sync is started immediately after the handshake, so a malicious user can get a few blocks after he or she gets banned.

The second thing to be discussed: is it OK to ban a user from whitelist? For me, it'll make harm to our system and we should avoid that.

Maybe it's more reasonable to add a few restrictions to Soma and Glienicke contracts:
1. A peer can be included to validators list or to whitelist only if it gets supermajority (can be implemented in IBFT level for validators)
2. Then it'd be possible to quickly find the highest block on a peer's chain that can be trusted to:
* ask about the highest block and check it's validators list. if it differs more than 1/3 of the node's current list, ignore the block
* ask for block (N_highest-N_current)/2 and check validators list

So we can use binary search to get highest trusted block from the peer in lg2(N_highest-N_current) steps and then repeat the process until sync all the blocks or find incorrect one. Until we get all correct blocks from the peer we shouldn't send it any of ours.

**Comment by yazzaoui** [comment]
> The thing is nowadays the sync is started immediately after the handshake, so a malicious user can get a few blocks after he or she gets banned.

Ok I have a this idea, instead of pausing relaying and block propagation for all our connected peers we do it only for this _specific untrusted_ peer . We do not allow him to sync through us if his TD is greater than ours because we are supposed to sync though him.  

So in practice we add a new flag "untrusted" for a eth peer and while his TD is greater than ours we set it true. Then we apply the following rules:

- in `eth/handler.go handleMsg(peer)`, we do not respond for an untrusted peer GetBlockHeaders, GetBlockBody GetNodeData, GetReceipts and all the sensitives msg codes.
- We do not sync transactions if untrusted, remove `pm.syncTransactions()`
 in protocol manager `handle(peer)`
- We do not send him mined blocks in protocol manager `BroadcastBlock()`
- We perform the switch untrusted -> trusted when his TD block is present in our local chain.

I believe with this solution we avoid putting in place the ban list, if he is malicious and not whitelisted, we will synchronise eventually through a legit peer and then we will kick him. Should as well prevent DoS issues. It avoid messing up with the complicated downloader logic and we keep flexibility for Glienicke/Soma.

Regarding your proposal, I don't understand really how supermajority could help but I get the point. I need to think more about it..

Another interesting thing that I was planning to studyis the sentry node architecture from [cosmos](https://forum.cosmos.network/t/sentry-node-architecture-overview/454) : I think that some other parts are vulnerable from DDOS/Sybil attacks in the system, need more investigation..

**Comment by JekaMas** [comment]
Won't it broke liveness property? AFAIK it's possible now to change the entire lists of validators or whitelist nodes:
1. A new block that changes whitelist/validators significantly or completely
2. If 2/3+1 approve it, 1/3-1 don't
3. if all of 2/3+1 nodes are still in the whitelist, then 1/3-1 won't be able to connect to the network if they lost connection with supermajority.
4. the supermajority will propose new and new blocks that could change validators and whitelist more and more
5. when 1/3-1 restore the connection they won't be able to get actual data because all peers they trust to were excluded from the lists and they can't get data from untrusted peers. So 1/3-1 can't connect to the network even if all of them are validators and in the whitelist.

At that case we'll need something like `reorg` mechanism, that sounds quite complicated.

**Comment by JekaMas** [comment]
@yazzaoui Do you have any thoughts about the last comment?

**Comment by yazzaoui** [comment]
I'm having a hard time understanding your scenario, perhaps you can detail a bit more because it's confusing (at least for me), @aneequesafdar please feel free to add your input as well

> If 2/3+1 approve it, 1/3-1 don't
 
My interpretation: those 1/3 - 1 are then malicious, the approval was handled by the Glieniecke contract logic, so those 1/3 - 1 node have no power in the decision. Make sense then to kick them from the system.

**Comment by JekaMas** [comment]
If someone doesn't approve a block it says to us nothing if them malicious or not.

**Comment by yazzaoui** [comment]
Wrong, if the block is valid and is coming from a valid proposer for a specific round then it **must** be approved by all the validators.
This is a fundamental concept for BFT style algorithms.

**Comment by JekaMas** [comment]
It could be a network issue, a node crash - a non-Bizantine fault, a normal fault.

**Comment by JekaMas** [comment]
In short:
1. If we keep trusting TD, we're affected to attack and anybody can real anything from the blockchain. It's exactly the same as Some contract doesn't work and we always have an open network.
2. If we're going to slash or ban users, if they not response, eg for sync request, we couldn't distinguish malicious users from users with bad connection or crashed server. This can lead us to the situation when a lot of good users are banned. I think nobody wants answer to bank worker at midnight, why they can't send or approve transaction.

3. As far as validators list is managed by the smart contract, its possible to change any number of validators even at a single block. If we can't trust to TD from the peer, this 2 condition can lead to the case when a honest validator can't join the network:
1. We have validators A,B,C,D,E
2. E goes offline
3. At that time A,B,C,D validators are changed to F,G,H,I while E is offline. The result validators list is F,G,H,I,E. E is still in the list.
4. E recovers after a crush/network issue
5. How can E sync with the network? It trust to old list of validators: A,B,C,D,E and A,B,C,D are not response. F,G,H,I will be trying to connect to E, hovewer E won't accept the connection. So there is no 'on-chain' or consensus solution for E to connect to the network even it is honest and in the list of validators.

For me, we need to re-thing permissioning, connectivity and sync of the network. We need not only a fix, but good, solid and provable solution.

**Comment by piersy** [comment]
I'm looking at this discussion now because I am explaining in the genesis docs how autonity uses the difficulty parameter.To use the difficulty parameter in the way that we are is clearly a misappropriation

**Comment by piersy** [comment]
I'm looking at this discussion now because I am trying to explain how we use the difficulty parameter in the genesis file documentation.

I think I may have a more simple approach to the ones discussed above.

When a node connects to my node another there are 4 possibilities for whitelist state.

| State | Action |
|----|----|
|They are in the whitelist but were added in a future block, so I don't see them in my whitelist| From my perspective they are not in the whitelist so I either disconnect them or only receive data from them untill such time as I see them in my whitelist, this choice depends on how mayny peers I'm connected to|
|They were in the whitelist but were removed in a previous block, so I don't see them in my whitelist| We take the same approach as above, since this peer may have been added again in a future block, we also allow this peer to sync up to the point at which it was removed from the whitelist.
|They were never in any whitelist| This situation is equvalent to the first|
|They are in the whitelist in the current block| We allow this peer to connect and send and receive data|

If we look at the actions above there are only 2 main courses of action.
* Disconnect the peer or only receive data from it.
* Send and receive data from the peer.

With the exception that:
* We allow peers who where previously in the whitelist but not in the current whitelist to sync up to the point at which they were in the whitelist.

We could actually re write this logic as 3 simple rules that we apply consistently.

* Receive data from all nodes.
* Only send data to nodes that are in the whitelist for that data, so if sending block X to a node check if that node is in the whitelist for block X. For all consensus protocol messages we only send them to nodes that are currently in the whitelist.
* Disconnect nodes only when we have exceeded our connection limits, we should have different connection limits for receive only and send/receive nodes.

@yazzaoui What do you think?

**Comment by yazzaoui** [comment]
Thanks for getting

>I'm looking at this discussion now because I am trying to explain how we use the difficulty parameter in the genesis file documentation.

The difficulty parameter will need to be removed from the genesis file configuration option, we need it to be equal to 1 in order for the system to be functioning, so let's just set by default at initialization.

The scheme you are proposing is very similar to one I've proposed (see https://github.com/clearmatics/autonity/issues/72#issuecomment-483885087) . A peer that you're connected to but not sending sensitive data to is what I called an untrusted peer. Concerning the connection limit you are suggesting, for the time being we will stick to a full graph topology, which has been tested scalable by Jason for our medium-term plans.
The optimal network topology is a complex subject, we need serious research work on it.

**Comment by piersy** [comment]
@yazzaoui 
> The scheme you are proposing is very similar to one I've proposed (see #72 (comment)) . A peer that you're connected to but not sending sensitive data to is what I called an untrusted peer.

Yes it is, except that it does not rely on TD or an untrusted flag, it simply enforces that peers cannot be sent data that they are not permitted to see.

>Concerning the connection limit you are suggesting, for the time being we will stick to a full graph topology, which has been tested scalable by Jason for our medium-term plans.

Sounds good :+1:

**Comment by piersy** [comment]
@yazzaoui I just wanted to elaborate on my thinking around the use of TD.

From the 2 rules you set out.

>1. If the peer total difficulty is greater than ours we accept the incoming connection
>2. If the peer is present in the local whitelist we accept the incoming connection. 

We can see that if the peer is in our whitelist then we do not need to consider its TD. The inspection of TD is only relevant when the peer is not in our whitelist.

In fact looking at the code, the only way connections are made is by attempting to connect to others in the whitelist and when nodes leave the whitelist we disconnect from them if their TD is not greater than ours.

If we imagine a network

What is the effect of TD in this situation?

It allows a node at newer block than us who sees us in its whitelist to open a connection to us that we would otherwise drop. This is needed so that we can sync, for example:
| Block Number | Whitelist Members |
|--------------------|---------------------------|
| 0 | A |
| 5 | B, C |
| 10 | B, C, D |

If node D has been added to whitelist in block 10 and is starting to sync and node A is no longer part of the network, it now has no way to connect into the network. It needs to wait for a connection from B or C who are not in its whitelist and through them it can sync to block 10. If we instead just used the whitelist to permission our peer connections then D would never be able to sync  since D would not allow connections from B or C and would therefore have no way to sync to block 10.

What about this situation?

| Block Number | Whitelist Members |
|--------------------|---------------------------|
| 0 | A, B, C |
| 10000 | A, B, C, D |

If we imagine that B and C are able to form consensus and build the chain to 10000 but A lost connection to B and C and has only made progress to 5000. Now D is added in block 10000 and starts to sync, D tries to connect to A, B and C but has its connection dropped by A because A does not see D in its whitelist.

We don't know when A will finish syncing, it could be a very long time, and during that time D will be renegotiating connections that will always be dropped by A. This is wasted work.

Also A could benefit from having a connection to D since D may be able to route transactions and block announcements to A that A was not able to receive directly from B and C.

I think we can see that we can get an improvement in reliable delivery and performance if we also allow connections to peers that have a lower TD and are not in our whitelist.

To ensure data is not leaked with this approach we simply need to ensure that nodes only send messages to nodes that are in their whitelist. But they may receive messages from nodes not in their whitelist. This is a much simpler approach than the current use of TD and eliminates the need for TD.

**Comment by Jason-Zhangxin-Chen** [comment]
> @yazzaoui I just wanted to elaborate on my thinking around the use of TD.
> 
> From the 2 rules you set out.
> 
> > 1. If the peer total difficulty is greater than ours we accept the incoming connection
> > 2. If the peer is present in the local whitelist we accept the incoming connection.
> 
> We can see that if the peer is in our whitelist then we do not need to consider its TD. The inspection of TD is only relevant when the peer is not in our whitelist.
> 
> In fact looking at the code, the only way connections are made is by attempting to connect to others in the whitelist and when nodes leave the whitelist we disconnect from them if their TD is not greater than ours.
> 
> If we imagine a network
> 
> What is the effect of TD in this situation?
> 
> It allows a node at newer block than us who sees us in its whitelist to open a connection to us that we would otherwise drop. This is needed so that we can sync, for example:
> 
> Block Number	Whitelist Members
> 0	A
> 5	B, C
> 10	B, C, D
> If node D has been added to whitelist in block 10 and is starting to sync and node A is no longer part of the network, it now has no way to connect into the network. It needs to wait for a connection from B or C who are not in its whitelist and through them it can sync to block 10. If we instead just used the whitelist to permission our peer connections then D would never be able to sync since D would not allow connections from B or C and would therefore have no way to sync to block 10.
> 
> What about this situation?
> 
> Block Number	Whitelist Members
> 0	A, B, C
> 10000	A, B, C, D
> If we imagine that B and C are able to form consensus and build the chain to 10000 but A lost connection to B and C and has only made progress to 5000. Now D is added in block 10000 and starts to sync, D tries to connect to A, B and C but has its connection dropped by A because A does not see D in its whitelist.
@piersy , in the case, B, C will tries to connect D, after D get synced, D tries to connect A, meanwhile, B, C and D will tries to connect and sync A, if A is start up, it will tries to connect B,C and get sync with D finaly.
> 
> We don't know when A will finish syncing, it could be a very long time, and during that time D will be renegotiating connections that will always be dropped by A. This is wasted work.
@piersy , this is the way dialing to find service or peer, in such case, D might have synced with B,C which have higher TD than A, and A would accept the connection request from D even A is un-sync with TD yet from B or C. And finaly A would get synced again.
> 
> Also A could benefit from having a connection to D since D may be able to route transactions and block announcements to A that A was not able to receive directly from B and C.
>  
> I think we can see that we can get an improvement in reliable delivery and performance if we also allow connections to peers that have a lower TD and are not in our whitelist.
> 
> To ensure data is not leaked with this approach we simply need to ensure that nodes only send messages to nodes that are in their whitelist. But they may receive messages from nodes not in their whitelist. This is a much simpler approach than the current use of TD and eliminates the need for TD.

**Comment by piersy** [comment]
Hi @Jason-Zhangxin-Chen 

>@piersy , in the case, B, C will tries to connect D, after D get synced, D tries to connect A, meanwhile, B, C and D will tries to connect and sync A, if A is start up, it will tries to connect B,C and get sync with D finally.

I don't think this is correct.

You say
>after D get synced, D tries to connect A,

D sees A in the whitelist from block 0, so D will be trying to connect to A before D has synced.

>@piersy , this is the way dialing to find service or peer, in such case, D might have synced with B,C which have higher TD than A, and A would accept the connection request from D even A is un-sync with TD yet from B or C. And finally A would get synced again.

So this is how the system would work now depending on TD, my point is that we can let D and A be connected before D has a higher TD than A and that this is good for the network since we don't waste work while D redials A.


Please let me know if I have misunderstood your points.
