### ISSUE TITLE
Node.js Console has a massive command line

### ISSUE THREAD

**Issue by flofrie** [autonity/autonity#737]
When looking at my process list with `ps ax`, NodeJS console seems to have a process that has an extremely long command line. It would be great if this could be avoided. (The screenshot below only shows _part_ of it.)

![image](https://user-images.githubusercontent.com/47421818/101520806-479f7c00-3985-11eb-9fb0-b654206e6216.png)

**Comment by piersy** [comment]
@flofrie haha, yes it is rather large!

The command-line for the *nodejs console* is actually not that large, its the line above the long line. The long line is in fact the command line for the nodejs child process spawned by the console.

Its large because we are passing js directly to node on the command line. The reason I chose this approach is because it means that you can contain the console in a single file. But I see that in fact our releases are bundling the `package-lock.json` with `console.sh` in a tar file so we've already lost the benefit of having a single file console, so I don't see any harm in separating the javascript into its own file.

**Comment by szemate** [comment]
@piersy why don't you just create an executable JavaScript file for the console with a `#!/usr/bin/env node` shebang?

The only extra thing the shell script does is installing the web3 node module, but it could just show an error message instead that tells the user "please run npm install web3" if it's not available. Then you wouldn't need any Bash code.

**Comment by piersy** [comment]
@szemate The script does a little more than just install web3, it also checks for node and npm and prints a useful message to the user if they are not installed.

When I was making this console I was trying to produce something that was as foolproof as possible and didn't need separate documentation. If we go for an executable javascript file then we will need to add a readme to cover installation of prerequisites for node at least.
