### ISSUE TITLE
Validator migration

### ISSUE THREAD

**Issue by mrostamii** [autonity/autonity#798]
### Description

In the context of managing validator nodes in Autonity, there's a need for clear guidance on validator migration. Specifically, the scenario is about when a validator node stops working or crashes, and we plan to move the keys and other data to a new AGC node with a different IP address.

Expected use cases include:
- Updating the enode URL IP:PORT address when it changes without creating a new validator identity/address.

The impact on the system and users is significant as it affects the continuity and reliability of the network. Clear guidelines on handling such cases will reduce downtime and potential system instability.

### Rationale

There needs to be more clarity about handling a scenario where a validator node crashes. We must move the validator's keys and other data to a new node in another region or data center with a new IP address. 

This feature is worthwhile as it will provide clarity to node operators and improve network resilience. 

### Implementation

While I don't have specific ideas on how this should be implemented, my current understanding is that:

1. The validator remains logically the same if the key is moved, meaning that re-computing and re-registering the validator isn't necessary.
2. The validator should be accessible at the same address.

However, this raises a few concerns:

- If the IP:PORT changes, what's the correct process to update the enode URL for the validator without creating a new validator identity?

Again, I cannot implement this feature, but I would appreciate some guidance from the Autonity team on these points. This information could be added to the Autonity documentation for future reference if suitable.

**Comment by yazzaoui** [comment]
Hi @mrostamii,
Thank you for your feedback, we indeed have in our roadmap the intent to integrate this feature for the upcoming Autonity mainnet but there are a few edge cases scenarios that we have still to figure out.
As of today, as long as a majority of our validators have correctly set up their IP addresses, it should be fine from a networking perspective. In the case of an IP migration, a redeployment of the client with a validator key previously used is fine as long as the previous validator node has been turned off. 

Special care is required on making sure that only one validator key is used per instance, otherwise, it would lead to a slashable offense
