### ISSUE TITLE
Committee selection reimplementation

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#870]
Consensus committee selection is done using quicksort at the protocol contract level.  
With a huge number of validators, this may not scale.

- [x] #886
- [x] #901
- [x] #922

**Comment by m4ksio** [comment]
While reviewing #892 I have noticed a few things which seems like they can speed up the selection process.
We first [iterate validator set](https://github.com/autonity/autonity/blob/4504e8acccca8ab65f8aba63a2674f51bc6250e6/autonity/solidity/contracts/Autonity.sol#L625) only to find the length.[ Later check](https://github.com/autonity/autonity/blob/4504e8acccca8ab65f8aba63a2674f51bc6250e6/autonity/solidity/contracts/Autonity.sol#L633) can be a part of loop to stop iteration if/when we hit the limit.
Instead, we can always pre-allocate max len anyway and cut one iteration, only keep the total number of elements filtered.

But I would propose different approach - just to keep the separate index of validators ordered by a stake. While doing any modification to the list we can find/update it in O(log2(n)) time. While in the worst case scenario, replacement of N validators would give us O(n * log2(n) but thats quicksort complexity anyway. I think this approach would allow us for much better amorization of computation time, and final selection would be akin to simply iterating over a list

**Comment by tbssajal** [comment]
> But I would propose different approach

@m4ksio could you please share details? I am not able to grasp the idea.

**Comment by yazzaoui** [comment]
I'm now considering that it might be acceptable to have a round change associated with a block that takes a prolonged time to process, once per epoch. This would be reasonable as long as the processing time stays below a certain threshold, for example, less than 10 seconds, and as long as the consequences are well understood and documented.

**Comment by m4ksio** [comment]
> could you please share details? I am not able to grasp the idea.

Sure. Currently, `computeCommittee()` does a lot of work, and its called once every epoch. It finds N highest staked active validators and form a new committee. It takes sort and few iterations over validators set to do this. What I propose is that instead of sorting in the function, we can already keep the sorted index and only read it to quickly select members.

For example. Over epoch we register validators A with stake 100, B with 300, C with 400 and D with 200.
Now we keep them inside `validatorList` simply by the order they were registered, so we have `[A, B, C, D]`. Later, in `computeCommittee` we sort this list by stake, getting `[C, B, D, A]` and get the committee from it (say we take only two, this selects `[C, B]`.
What I propose is a separate index which is modified at the time of registration. This index is ordered by stake, and updated when we register/deregister validators. Something like this.
register A - index becomes `[A]`
B - index becomes `[B, A]`
C - `[C, B, A]`
D - `[C, B, D, A]`
later, `computeCommittee` can simply grab N validators from this index. 

Insertion/removal to ordered index has `O(log2(n))` complexity. So adding N elements will have a total of `O(N*log2(N))` - which is the same complexity as sorting - but it will be amortized over time. Moreover, if we don't really add/remove many new validators (which I think we won't) there is no extra computation required.

I know that our flow for adding validators is a bit more complex - ie we only register requests and process them at the epoch, but that doesn't mean that the principle cannot be applied.

**Comment by tbssajal** [comment]
I see @m4ksio thanks. But the problem is the stakes can also change for bonding, unbonding and slashing and all of these operations are applied at the epoch end before selecting the committee. We can consider that each validator's stake will change at most once by adding up all bonding amount, unbonding amount and slashed amount, but even then we may need to change stakes of many validators. If we apply this method for each change in the stake of the validator at the epoch end, will it still be amortized N*logN and faster than sorting?

**Comment by tbssajal** [comment]
> I'm now considering that it might be acceptable to have a round change associated with a block that takes a prolonged time to process, once per epoch.

I kinda agree. Even though we are benchmarking the committee selection process, there are other things we are not benchmarking like bonding, unbonding and slashing processes. The number of slashing done in one epoch could be very low, but bonding and unbonding can be requested externally and all of them are processed at the epoch end. It also creates scope to spam requests, because bonding and unbonding requests for any positive amount are valid and processed. So one can send requests for bonding/unbonding only 1 wei. It will just cost him some gas. It may also be necessary to keep the final block for these operations only and no other transactions.
