### ISSUE TITLE
Parallel signature verification

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#878]
Currently, consensus message signature verification happens twice, one time during core processing and one time in the fault detector. This is very resource-costly, the signature verification needs to happen ideally upfront in the sender's message handler go-routine.

**Comment by lorenzo-dev1** [comment]
Unassigning myself for the moment since:
1. Depending on how/if we will implement [BLS signatures](https://github.com/autonity/autonity/issues/869), this might not be required / only parts of it might be required
2. 95% completed version (lacks only minor refinements) is already available for review at https://github.com/autonity/autonity/pull/881

**Comment by yazzaoui** [comment]
We can probably close this issue @lorenzo-dev1 as this has been depreciated ?

**Comment by lorenzo-dev1** [comment]
Yes, this will be instead dealt with by the BLS aggregator.
