### ISSUE TITLE
Tests for current implementation of Network permissioning

### ISSUE THREAD

**Issue by IronGauntlets** [autonity/autonity#91]
In order to be more confident that we are not introducing breaking changes in Autonity client and produce production quality code, we need to accompany any substantial changes we make with Tests, I believe as of right now the major changes introduced by network permissioning does not have tests.

**Comment by JekaMas** [comment]
I was thinking about it. Maybe we need a combination of unit tests and a batch of e2e with property based testing.

Maybe we can try something like this steps:
1. Test Soma and Glienicke contracts.
2. Check are the contracts safe
3. Unit tests on network permissioning
4. E2e tests with property based testing: there's no such conditions when untrasted peer gets blockchain data; there's no such conditions when trusted peer can't get the latest blockchain data; there's no such conditions when validator can't participate in validating the block; there's no such conditions when current proposer can't send the proposal to the chain.
5. Try different network permissioning models.

@aneequesafdar

**Comment by daragao** [comment]
One of the biggest problems me and @maxrobot had when developing the first iteration of the permission was to make sure on Soma, that the consensus was still working correctly, and nodes were reacting in a controlled manner (not failing due to errors).

This was very dependent on E2E tests that allowed to make changes always in the same way to the state (adding one validator, and removing another in the same block, or removing a validator and adding another one before it was the old validator turn to sign again a block).

We started making some scripts for deployment, and control of when state was changed, but never really finished. This would be a great addition even to other features that might affect the consensus (like a gas token).

**Comment by JekaMas** [comment]
Why we don't use events in Soma and Glienicke? It'd be a lot simpler to subscribe to events from golang code or js truffle tests that trying to control when state was changed.

**Comment by JekaMas** [comment]
Hmm... I've found a good example of property based testing for smart contracts - https://github.com/windingtree/lif-token/pull/60

**Comment by aneequesafdar** [comment]
referring network permissioning issue #72
